### ISSUE TITLE
Some sunset times broken

### ISSUE THREAD

**Issue by kristephe** [kdknigga/loggingnight#24]
Northern Washington sunsets like KNUW and KBLI are showing AM times. KSLE was normal. 
![Screenshot_20230705-000942](https://github.com/kdknigga/loggingnight/assets/138656083/98734548-cff7-495a-b634-ccb6ccbc1c3a)

![Screenshot_20230705-000817](https://github.com/kdknigga/loggingnight/assets/138656083/c4154af4-ec2f-4416-827f-5fc84b3a3ec8)

**Comment by kdknigga** [comment]
That's interesting.  Thanks for reporting.

**Comment by kdknigga** [comment]
I'm not sure why the astronomy package I was using was giving those goofy times (and only in July?), but the USNO's service is back online, and I've switched back to using it.  This has resolved this problem.
